
spring:
  profiles:
    active: window-dev
---
server:
  port: 8080

logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: window-dev
  application:
    name: flex-main

api:
  uri:
    employee: localhost:8081
    
---

server:
  port: 8080
              
logging:
  level:
    yongs:
      temp: DEBUG
    
spring:
  profiles: docker-dev
  application:
    name: flex-main

api:
  uri:
    employee: ${EMPLOYEE_URL}    